---
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Generate kafka cluster id
    shell: |
      uuidgen | tr -d '-' | base64 | cut -b 1-22
    args:
      executable: /bin/bash
    register: etcd_initial_token
    run_once: yes
    delegate_to: localhost
    become: no